services:

  taxajuros:
      build:
          context: Microservices/TaxaJuros/
          dockerfile: Microservices/TaxaJuros/Dockerfile

  calculajuros:
      build:
          context: Microservices/CalculaJuros/
          dockerfile: Microservices/CalculaJuros/Dockerfile

  gateway:
      build:
          context: Gateway/
          dockerfile: Gateway/Dockerfile