services:

  taxajuros:
    container_name: taxajuros
    hostname: taxajuros
    build:
      context: ./Microservices/TaxaJuros/

  calculajuros:
    container_name: calculajuros
    hostname: calculajuros
    build:
      context: ./Microservices/CalcularJuros/

  gateway:
    container_name: gateway
    hostname: gateway
    build:
      context: ./Gateway/