services:

  taxajuros:
      build:
          context: Microservices/TaxaJuros/
          dockerfile: Microservices/TaxaJuros/Dockerfile

  calculajuros:
      build:
          context: Microservices/CalcularJuros/
          dockerfile: Microservices/CalcularJuros/Dockerfile

  gateway:
      build:
          context: Gateway/
          dockerfile: Gateway/Dockerfile