services:

  taxajuros:
      build:
          context: .
          dockerfile: Microservices/TaxaJuros/Dockerfile

  calculajuros:
      build:
          context: .
          dockerfile: Microservices/CalcularJuros/Dockerfile

  gateway:
      build:
          context: .
          dockerfile: Gateway/Dockerfile